<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MonoGame.ImPlotNet.Sample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui"  Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImPlot" Version="2.2.9" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoGame.ImPlot\MonoGame.ImPlot.csproj" />
  </ItemGroup>

</Project>
